### ISSUE TITLE
Unhandled Rejection when calling some methods without a detectable wallet address

### ISSUE THREAD

**Issue by smokeynotes** [CaskProtocol/cask-js-sdk#12]
The following lines produce an `Unhandled Rejection` exception if no wallet address can be determined.  

https://github.com/CaskProtocol/cask-js-sdk/blob/3c999b7afae015ebd160ce16203f3dc456f3131d/src/query/index.js#L306
https://github.com/CaskProtocol/cask-js-sdk/blob/3c999b7afae015ebd160ce16203f3dc456f3131d/src/query/index.js#L333

![Screen Shot 2022-07-14 at 10 02 30 AM](https://user-images.githubusercontent.com/95720472/179040179-396430b1-e1f7-4dee-a6e1-bc1e88083bca.png)

Suggest checking for an undefined value before using the wallet address in a where condition.  Throwing an exception indicating a wallet address could not be found would be a more digestible error message.  This would be consistent with some of the other summary methods and the `flows` method that `throw new Error("address not specified or detectable");`.  

Also, if the intent is to allow this method to be called for other wallet addresses or disconnected wallets, it may be a good idea to allow an address to be passed in as a parameter.  I understand this can be accomplished by specifying an address within the `where` parameter manually, but allowing for an address to be passed in is already a pattern being used in other methods such as the summary methods and the `flows` method.

It also seems there are 2 different ways of checking for the address to be used....`currentWalletAddress()` and `address = address || this.ethersConnection.address`, so unsure if this inconsistency has a functional purpose.

**Comment by masha256** [comment]
@smokeynotes Cleaned up, latest `main` has updated.
